const joi = require('joi');
const {
  options, isCountOnly, include, select 
} = require('../commonFilterValidation');

const createSchema = joi.object({
  default_category_id: joi.number().integer().allow(0),
  other_category_ids: joi.string().allow(null).allow(''),
  name: joi.string().allow(null).allow(''),
  brand_id: joi.number().integer().allow(0),
  image_ids: joi.string().allow(null).allow(''),
  description: joi.string().allow(null).allow(''),
  short_description: joi.string().allow(null).allow(''),
  video_link: joi.string().allow(null).allow(''),
  product_type: joi.string().allow(null).allow(''),
  regular_price: joi.number().integer().allow(0),
  sale_price: joi.number().integer().allow(0),
  tax_status: joi.string().allow(null).allow(''),
  tax_claas: joi.string().allow(null).allow(''),
  SKU: joi.string().allow(null).allow(''),
  stock_quantity: joi.number().integer().allow(0),
  allow_backorders: joi.string().allow(null).allow(''),
  low_stock_threshold: joi.number().integer().allow(0),
  sold_individually: joi.number().integer().allow(0),
  weight_value: joi.number().integer().allow(0),
  weight_unit: joi.number().integer().allow(0),
  length: joi.number().integer().allow(0),
  shipping_class: joi.string().allow(null).allow(''),
  purchase_note: joi.string().allow(null).allow(''),
  product_tagid: joi.number().integer().allow(0),
  menu_order: joi.number().integer().allow(0),
  enable_reviews: joi.number().integer().allow(0),
  width: joi.number().integer().allow(0),
  height: joi.number().integer().allow(0),
  breadth: joi.number().integer().allow(0),
  dimension_unit: joi.number().integer().allow(0),
  linked_product_id: joi.number().integer().allow(0),
  cross_sell_id: joi.number().integer().allow(0),
  hsn_code_id: joi.number().integer().allow(0),
  isDeleted: joi.boolean(),
  isActive: joi.boolean()
}).unknown(true);

const updateSchema = joi.object({
  default_category_id: joi.number().integer().allow(0),
  other_category_ids: joi.string().allow(null).allow(''),
  name: joi.string().allow(null).allow(''),
  brand_id: joi.number().integer().allow(0),
  image_ids: joi.string().allow(null).allow(''),
  description: joi.string().allow(null).allow(''),
  short_description: joi.string().allow(null).allow(''),
  video_link: joi.string().allow(null).allow(''),
  product_type: joi.string().allow(null).allow(''),
  regular_price: joi.number().integer().allow(0),
  sale_price: joi.number().integer().allow(0),
  tax_status: joi.string().allow(null).allow(''),
  tax_claas: joi.string().allow(null).allow(''),
  SKU: joi.string().allow(null).allow(''),
  stock_quantity: joi.number().integer().allow(0),
  allow_backorders: joi.string().allow(null).allow(''),
  low_stock_threshold: joi.number().integer().allow(0),
  sold_individually: joi.number().integer().allow(0),
  weight_value: joi.number().integer().allow(0),
  weight_unit: joi.number().integer().allow(0),
  length: joi.number().integer().allow(0),
  shipping_class: joi.string().allow(null).allow(''),
  purchase_note: joi.string().allow(null).allow(''),
  product_tagid: joi.number().integer().allow(0),
  menu_order: joi.number().integer().allow(0),
  enable_reviews: joi.number().integer().allow(0),
  width: joi.number().integer().allow(0),
  height: joi.number().integer().allow(0),
  breadth: joi.number().integer().allow(0),
  dimension_unit: joi.number().integer().allow(0),
  linked_product_id: joi.number().integer().allow(0),
  cross_sell_id: joi.number().integer().allow(0),
  hsn_code_id: joi.number().integer().allow(0),
  isDeleted: joi.boolean(),
  isActive: joi.boolean(),
  id: joi.number().integer()
}).unknown(true);

let keys = ['query', 'where'];
let filterValidationSchema = joi.object({
  options: options,
  ...Object.fromEntries(keys.map(key => [key, joi.object({
    default_category_id: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    other_category_ids: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
    name: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
    brand_id: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    image_ids: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
    description: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
    short_description: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
    video_link: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
    product_type: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
    regular_price: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    sale_price: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    tax_status: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
    tax_claas: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
    SKU: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
    stock_quantity: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    allow_backorders: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
    low_stock_threshold: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    sold_individually: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    weight_value: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    weight_unit: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    length: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    shipping_class: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
    purchase_note: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
    product_tagid: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    menu_order: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    enable_reviews: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    width: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    height: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    breadth: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    dimension_unit: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    linked_product_id: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    cross_sell_id: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    hsn_code_id: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
    isDeleted: joi.alternatives().try(joi.array().items(),joi.boolean(),joi.object()),
    isActive: joi.alternatives().try(joi.array().items(),joi.boolean(),joi.object()),
    id: joi.any()
  }).unknown(true),])),
  isCountOnly: isCountOnly,
  include: joi.array().items(include),
  select: select
}).unknown(true);

module.exports = {
  createSchema,
  updateSchema,
  filterValidationSchema
};